/**
 * @file InputTypes.hpp
 * @brief Defines basic types for keyboard events and editor actions.
 */
#pragma once
#include <cstdint>

namespace pluma {

/**
 * @enum ModifierFlags
 * @brief Bitmask for keyboard modifiers.
 */
enum class ModifierFlags : uint32_t {
    None    = 0,
    Shift   = 1 << 0,
    Control = 1 << 1,
    Alt     = 1 << 2,
    Super   = 1 << 3
};

inline ModifierFlags operator|(ModifierFlags a, ModifierFlags b) {
    return static_cast<ModifierFlags>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
}

inline ModifierFlags operator&(ModifierFlags a, ModifierFlags b) {
    return static_cast<ModifierFlags>(static_cast<uint32_t>(a) & static_cast<uint32_t>(b));
}

inline bool hasModifier(ModifierFlags flags, ModifierFlags check) {
    return (static_cast<uint32_t>(flags) & static_cast<uint32_t>(check)) != 0;
}

/**
 * @enum MouseButton
 * @brief Identifies buttons on a mouse device.
 */
enum class MouseButton : uint8_t {
    None,
    Left,
    Right,
    Middle,
    Back,
    Forward
};

/**
 * @enum EditorAction
 * @brief Standardized actions generated by the InputRouter.
 */
enum class EditorAction {
    None,
    InsertText,
    DeleteBackward,
    DeleteForward,
    Undo,
    Redo,
    MoveCursorLeft,
    MoveCursorRight,
    MoveCursorLeftWord,
    MoveCursorRightWord,
    MoveCursorUp,
    MoveCursorDown,
    Copy,
    Paste,
    Cut,
    ToggleInsertMode
};

/**
 * @enum InsertMode
 * @brief Text insertion behavior mode.
 */
enum class InsertMode {
    Insert,
    Replace
};

} // namespace pluma
